//generated by lazy
//author: seanlan

package v1

import (
	"github.com/gin-gonic/gin"
	"token-payment/internal/e"
	"token-payment/internal/model"
	"token-payment/internal/service"
	"token-payment/pkg/xlhttp"
)

func AdminLogin(c *gin.Context) {
	var (
		err error
	)
	r := xlhttp.Build(c)

	var req model.AdminLoginReq
	err = r.RequestParser(&req)
	if err != nil {
		return
	}
	req.ClientIP = c.ClientIP()
	resp, err := service.AdminLogin(c, req)
	r.JsonReturn(err, resp)
	return
}

func AdminLogout(c *gin.Context) {
	var (
		err    error
		userID int64
	)
	r := xlhttp.Build(c)
	userID, err = r.GetJWTUID()
	if userID == 0 || err != nil {
		r.JsonReturn(e.ErrorToken)
		return
	}
	var req model.AdminLogoutReq
	err = r.RequestParser(&req)
	if err != nil {
		return
	}
	req.UserID = userID
	req.ClientIP = c.ClientIP()
	resp, err := service.AdminLogout(c, req)
	r.JsonReturn(err, resp)
	return
}
func AdminChangePassword(c *gin.Context) {
	var (
		err    error
		userID int64
	)
	r := xlhttp.Build(c)
	userID, err = r.GetJWTUID()
	if userID == 0 || err != nil {
		r.JsonReturn(e.ErrorToken)
		return
	}
	var req model.AdminChangePasswordReq
	err = r.RequestParser(&req)
	if err != nil {
		return
	}
	req.UserID = userID
	req.ClientIP = c.ClientIP()
	resp, err := service.AdminChangePassword(c, req)
	r.JsonReturn(err, resp)
	return
}

func GetAdminInfo(c *gin.Context) {
	var (
		err    error
		userID int64
	)
	r := xlhttp.Build(c)
	userID, err = r.GetJWTUID()
	if userID == 0 || err != nil {
		r.JsonReturn(e.ErrorToken)
		return
	}
	var req model.GetAdminInfoReq
	err = r.RequestParser(&req)
	if err != nil {
		return
	}
	req.UserID = userID
	req.ClientIP = c.ClientIP()
	resp, err := service.GetAdminInfo(c, req)
	r.JsonReturn(err, resp)
	return
}
