//generated by lazy
//author: seanlan

package v1

import (
	"github.com/gin-gonic/gin"
	"token-payment/internal/e"
	"token-payment/internal/model"
	"token-payment/internal/service"
	"token-payment/pkg/xlhttp"
)

func GetApplicationList(c *gin.Context) {
	var (
		err    error
		userID int64
	)
	r := xlhttp.Build(c)
	userID, err = r.GetJWTUID()
	if userID == 0 || err != nil {
		r.JsonReturn(e.ErrorToken)
		return
	}
	var req model.GetApplicationListReq
	err = r.RequestParser(&req)
	if err != nil {
		return
	}
	req.UserID = userID
	req.ClientIP = c.ClientIP()
	resp, err := service.GetApplicationList(c, req)
	r.JsonReturn(err, resp)
	return
}

func EditApplication(c *gin.Context) {
	var (
		err    error
		userID int64
	)
	r := xlhttp.Build(c)
	userID, err = r.GetJWTUID()
	if userID == 0 || err != nil {
		r.JsonReturn(e.ErrorToken)
		return
	}
	var req model.EditApplicationReq
	err = r.RequestParser(&req)
	if err != nil {
		return
	}
	req.UserID = userID
	req.ClientIP = c.ClientIP()
	resp, err := service.EditApplication(c, req)
	r.JsonReturn(err, resp)
	return
}
