//generated by lazy
//author: seanlan

package v1

import (
	"github.com/gin-gonic/gin"
	"token-payment/internal/e"
	"token-payment/internal/model"
	"token-payment/internal/service"
	"token-payment/pkg/xlhttp"
)

func GetChainList(c *gin.Context) {
	var (
		err    error
		userID int64
	)
	r := xlhttp.Build(c)
	userID, err = r.GetJWTUID()
	if userID == 0 || err != nil {
		r.JsonReturn(e.ErrorToken)
		return
	}
	var req model.GetChainListReq
	err = r.RequestParser(&req)
	if err != nil {
		return
	}
	req.UserID = userID
	req.ClientIP = c.ClientIP()
	resp, err := service.GetChainList(c, req)
	r.JsonReturn(err, resp)
	return
}
func EditChain(c *gin.Context) {
	var (
		err    error
		userID int64
	)
	r := xlhttp.Build(c)
	userID, err = r.GetJWTUID()
	if userID == 0 || err != nil {
		r.JsonReturn(e.ErrorToken)
		return
	}
	var req model.EditChainReq
	err = r.RequestParser(&req)
	if err != nil {
		return
	}
	req.UserID = userID
	req.ClientIP = c.ClientIP()
	resp, err := service.EditChain(c, req)
	r.JsonReturn(err, resp)
	return
}
func GetChainRPCList(c *gin.Context) {
	var (
		err    error
		userID int64
	)
	r := xlhttp.Build(c)
	userID, err = r.GetJWTUID()
	if userID == 0 || err != nil {
		r.JsonReturn(e.ErrorToken)
		return
	}
	var req model.GetChainRPCListReq
	err = r.RequestParser(&req)
	if err != nil {
		return
	}
	req.UserID = userID
	req.ClientIP = c.ClientIP()
	resp, err := service.GetChainRPCList(c, req)
	r.JsonReturn(err, resp)
	return
}
func EditChainRPC(c *gin.Context) {
	var (
		err    error
		userID int64
	)
	r := xlhttp.Build(c)
	userID, err = r.GetJWTUID()
	if userID == 0 || err != nil {
		r.JsonReturn(e.ErrorToken)
		return
	}
	var req model.EditChainRPCReq
	err = r.RequestParser(&req)
	if err != nil {
		return
	}
	req.UserID = userID
	req.ClientIP = c.ClientIP()
	resp, err := service.EditChainRPC(c, req)
	r.JsonReturn(err, resp)
	return
}

func DeleteChainRPC(c *gin.Context) {
	var (
		err    error
		userID int64
	)
	r := xlhttp.Build(c)
	userID, err = r.GetJWTUID()
	if userID == 0 || err != nil {
		r.JsonReturn(e.ErrorToken)
		return
	}
	var req model.DeleteChainRPCReq
	err = r.RequestParser(&req)
	if err != nil {
		return
	}
	req.UserID = userID
	req.ClientIP = c.ClientIP()
	resp, err := service.DeleteChainRPC(c, req)
	r.JsonReturn(err, resp)
	return
}

func GetTokenList(c *gin.Context) {
	var (
        err    error
        userID int64
    )
    r := xlhttp.Build(c)
    userID, err = r.GetJWTUID()
    if userID == 0 || err != nil {
        r.JsonReturn(e.ErrorToken)
        return
    }
    var req model.GetTokenListReq
    err = r.RequestParser(&req)
    if err != nil {
        return
    }
    req.UserID = userID
    req.ClientIP = c.ClientIP()
    resp, err := service.GetTokenList(c, req)
    r.JsonReturn(err, resp)
    return
}
func EditToken(c *gin.Context) {
	var (
        err    error
        userID int64
    )
    r := xlhttp.Build(c)
    userID, err = r.GetJWTUID()
    if userID == 0 || err != nil {
        r.JsonReturn(e.ErrorToken)
        return
    }
    var req model.EditTokenReq
    err = r.RequestParser(&req)
    if err != nil {
        return
    }
    req.UserID = userID
    req.ClientIP = c.ClientIP()
    resp, err := service.EditToken(c, req)
    r.JsonReturn(err, resp)
    return
}
func DeleteToken(c *gin.Context) {
	var (
        err    error
        userID int64
    )
    r := xlhttp.Build(c)
    userID, err = r.GetJWTUID()
    if userID == 0 || err != nil {
        r.JsonReturn(e.ErrorToken)
        return
    }
    var req model.DeleteTokenReq
    err = r.RequestParser(&req)
    if err != nil {
        return
    }
    req.UserID = userID
    req.ClientIP = c.ClientIP()
    resp, err := service.DeleteToken(c, req)
    r.JsonReturn(err, resp)
    return
}