//generated by lazy
//author: seanlan

package v1

import (
	"github.com/gin-gonic/gin"
	"token-payment/internal/model"
	"token-payment/internal/service"
	"token-payment/pkg/xlhttp"
)

func CreatePaymentAddress(c *gin.Context) {
	var (
		err error
	)
	r := xlhttp.Build(c)
	var req model.CreatePaymentAddressReq
	err = r.RequestParser(&req)
	if err != nil {
		return
	}
	req.ClientIP = c.ClientIP()
	resp, err := service.CreatePaymentAddress(c, req)
	r.JsonReturn(err, resp)
	return
}

func Withdraw(c *gin.Context) {
	var (
		err error
	)
	r := xlhttp.Build(c)

	var req model.WithdrawReq
	err = r.RequestParser(&req)
	if err != nil {
		return
	}
	req.ClientIP = c.ClientIP()
	resp, err := service.Withdraw(c, req)
	r.JsonReturn(err, resp)
	return
}
