//generated by lazy
//author: seanlan

package model

type AdminLoginReq struct {
	BaseReq
	Username string `json:"username" form:"username" binding:"required"`
	Password string `json:"password" form:"password" binding:"required"`
}

type AdminLoginResp struct {
	Token string `json:"token"`
}

type AdminLogoutReq struct {
	BaseReq
}

type AdminLogoutResp struct {
}

type AdminChangePasswordReq struct {
	BaseReq
	NewPassword string `json:"new_password" form:"new_password" binding:"required"`
}

type AdminChangePasswordResp struct {
}

type GetAdminInfoReq struct {
	BaseReq
}

type GetAdminInfoResp struct {
	ID     int      `json:"id"`
	Avatar string   `json:"avatar"`
	Name   string   `json:"name"`
	Roles  []string `json:"roles"`
}
