//generated by lazy
//author: seanlan

package model

import "token-payment/internal/dao/sqlmodel"

type GetChainListReq struct {
	BaseReq
	Page int `json:"page" form:"page" binding:"required"`
	Size int `json:"size" form:"size" binding:"required"`
}

type GetChainListResp struct {
	List  []sqlmodel.Chain `json:"list"`
	Total int64            `json:"total"`
}

type EditChainReq struct {
	BaseReq
	ID          int64  `json:"id" form:"id"`
	ChainSymbol string `json:"chain_symbol" form:"chain_symbol" binding:"required"`
	Name        string `json:"name" form:"name" binding:"required"`
	ChainID     int64  `json:"chain_id" form:"chain_id"`
	Currency    string `json:"currency" form:"currency"`
	ChainType   string `json:"chain_type" form:"chain_type" binding:"required"`
	Confirm     int32  `json:"confirm" form:"confirm"`
	Gas         int64  `json:"gas" form:"gas"`
	GasPrice    int64  `json:"gas_price" form:"gas_price"`
	Concurrent  int32  `json:"concurrent" form:"concurrent" binding:"required"`
	Watch       int32  `json:"watch" form:"watch"`
}

type EditChainResp struct {
}

type GetChainRPCListReq struct {
	BaseReq
	ChainSymbol string `json:"chain_symbol" form:"chain_symbol"`
	Page        int    `json:"page" form:"page" binding:"required"`
	Size        int    `json:"size" form:"size" binding:"required"`
}

type GetChainRPCListResp struct {
	List  []sqlmodel.ChainRPC `json:"list"`
	Total int64               `json:"total"`
}

type EditChainRPCReq struct {
	BaseReq
	ID          int64  `json:"id" form:"id"`
	ChainSymbol string `json:"chain_symbol" form:"chain_symbol" binding:"required"`
	RPCUrl      string `json:"rpc_url" form:"rpc_url" binding:"required"`
	Disable     int32  `json:"disable" form:"disable"`
}

type EditChainRPCResp struct {
}

type DeleteChainRPCReq struct {
	BaseReq
	ID int64 `json:"id" form:"id" binding:"required"`
}

type DeleteChainRPCResp struct {
}

type GetTokenListReq struct {
	BaseReq
	ChainSymbol string `json:"chain_symbol" form:"chain_symbol" binding:"required"`
	Page        int    `json:"page" form:"page" binding:"required"`
	Size        int    `json:"size" form:"size" binding:"required"`
}

type GetTokenListResp struct {
	List  []sqlmodel.ChainToken `json:"list"`
	Total int64                 `json:"total"`
}

type EditTokenReq struct {
	BaseReq
	ID              int64   `json:"id" form:"id" binding:"required"`
	ChainSymbol     string  `json:"chain_symbol" form:"chain_symbol" binding:"required"`
	ContractAddress string  `json:"contract_address" form:"contract_address"`
	Name            string  `json:"name" form:"name" binding:"required"`
	Symbol          string  `json:"symbol" form:"symbol" binding:"required"`
	Decimals        int32   `json:"decimals" form:"decimals" binding:"required"`
	Threshold       float64 `json:"threshold" form:"threshold"`
	GasFee          float64 `json:"gas_fee" form:"gas_fee"`
	ArrangeSwitch   int32   `json:"arrange_switch" form:"arrange_switch"`
}

type EditTokenResp struct {
}

type DeleteTokenReq struct {
	BaseReq
	ID int64 `json:"id" form:"id" binding:"required"`
}

type DeleteTokenResp struct {
}
