//generated by lazy
//author: seanlan

package model

type GetAllGroupReq struct {
	BaseReq
}

type Group struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Permissions []int  `json:"permissions"`
}

type GetAllGroupResp struct {
	List []Group `json:"list"`
}

type AddGroupReq struct {
	BaseReq
	Name        string `json:"name"`
	Permissions []int  `json:"permissions"`
}

type AddGroupResp struct {
}

type EditGroupReq struct {
	BaseReq
	GroupID     int64  `json:"group_id"`
	Name        string `json:"name"`
	Permissions []int  `json:"permissions"`
}

type EditGroupResp struct {
}
