//generated by lazy
//author: seanlan

package model

import "token-payment/internal/dao/sqlmodel"

type GetAllPermissionReq struct {
	BaseReq
}

type PermissionType struct {
	Type        string                     `json:"type"`
	Permissions []sqlmodel.AdminPermission `json:"permissions"`
}

type GetAllPermissionResp struct {
	List []PermissionType `json:"list"`
}
