//generated by lazy
//author: seanlan

package model

import "token-payment/internal/dao/sqlmodel"

type UserSimple struct {
	ID       int    `json:"id"`
	Account  string `json:"account"`
	Username string `json:"username"`
	IsSuper  int    `json:"is_super"`
}

type AddStaffReq struct {
	BaseReq
	Account     string `json:"account" form:"account" binding:"required"`
	Password    string `json:"password" form:"password" binding:"required"`
	Username    string `json:"username" form:"username" binding:"required"`
	Phone       string `json:"phone" form:"phone" binding:"omitempty"`
	Email       string `json:"email" form:"email" binding:"omitempty"`
	Group       int64  `json:"group" form:"group" binding:"omitempty"`             // 用户组
	Permissions []int  `json:"permissions" form:"permissions" binding:"omitempty"` // 权限
}

type AddStaffResp struct {
}

type StaffListReq struct {
	BaseReq
	Page int `json:"page" form:"page" binding:"omitempty"`
	Size int `json:"size" form:"size" binding:"omitempty"`
}

type GroupInfo struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type StaffItem struct {
	ID          int64  `json:"id"`
	Account     string `json:"account"`
	Username    string `json:"username"`
	Phone       string `json:"phone"`
	Email       string `json:"email"`
	GroupID     int64  `json:"group_id"`
	GroupName   string `json:"group_name"`
	IsSuper     int32  `json:"is_super"`
	IsFrozen    int32  `json:"is_frozen"`
	HideArticle int32  `json:"hide_article"`
	CreateAt    int64  `json:"create_at"`
}

type StaffListResp struct {
	List  []StaffItem `json:"list"`
	Total int64       `json:"total"`
}

type EditStaffReq struct {
	BaseReq
	StaffID     int64  `json:"staff_id" form:"staff_id" binding:"required"`
	Username    string `json:"username" form:"username" binding:"required"`
	Phone       string `json:"phone" form:"phone" binding:"omitempty"`
	Email       string `json:"email" form:"email" binding:"omitempty"`
	Group       int64  `json:"group" form:"group" binding:"omitempty"`             // 用户组
	Permissions []int  `json:"permissions" form:"permissions" binding:"omitempty"` // 权限
}

type EditStaffResp struct {
}

type StaffInfoReq struct {
	BaseReq
	StaffID int64 `json:"staff_id" form:"staff_id" binding:"required"`
}

type StaffInfo struct {
	ID               int64  `json:"id"`
	Account          string `json:"account"`
	Username         string `json:"username"`
	Phone            string `json:"phone"`
	Email            string `json:"email"`
	CreateAt         int64  `json:"create_at"`
	Group            int    `json:"group"`
	GroupPermissions []int  `json:"group_permissions"`
	Permissions      []int  `json:"permissions"`
}

type StaffInfoResp struct {
	Staff StaffInfo `json:"staff"`
}

type StaffFrozenReq struct {
	BaseReq
	StaffID  int64 `json:"staff_id" form:"staff_id" binding:"required"`
	IsFrozen int32 `json:"is_frozen" form:"is_frozen"`
}

type StaffFrozenResp struct {
}

type StaffRePasswordReq struct {
	BaseReq
	StaffID  int64  `json:"staff_id" form:"staff_id" binding:"required"`
	Password string `json:"password" form:"password" binding:"required"`
}

type StaffRePasswordResp struct {
}

type StaffLogsReq struct {
	BaseReq
	StaffID   int64  `json:"staff_id" form:"staff_id"`
	DateStart string `json:"date_start" form:"date_start"`
	DateEnd   string `json:"date_end" form:"date_end"`
	Page      int    `json:"page" form:"page" binding:"required"`
	Size      int    `json:"size" form:"size" binding:"required"`
}

type StaffLogItem struct {
	sqlmodel.AdminLog
	Staff UserSimple `json:"staff"`
}

type StaffLogsResp struct {
	List  []StaffLogItem `json:"list"`
	Total int64          `json:"total"`
}
