//generated by lazy
//author: seanlan

package service

import (
	"context"
	"fmt"
	"golang.org/x/crypto/bcrypt"
	"token-payment/internal/dao"
	"token-payment/internal/dao/sqlmodel"
	"token-payment/internal/e"
	"token-payment/internal/handler"
	"token-payment/internal/model"
)

func AdminLogin(ctx context.Context, req model.AdminLoginReq) (resp model.AdminLoginResp, err error) {
	var (
		admin          sqlmodel.AdminUser
		adminQ         = sqlmodel.AdminUserColumns
		adminUserToken sqlmodel.AdminUserToken
	)
	err = dao.FetchAdminUser(ctx, &admin, adminQ.Account.Eq(req.Username))
	if err != nil {
		err = e.ErrorUsernameOrPassword
		return
	}
	err = bcrypt.CompareHashAndPassword([]byte(admin.Password), []byte(req.Password))
	if err != nil {
		err = e.ErrorUsernameOrPassword
		return
	}
	adminUserToken, err = handler.GenUserToken(ctx, admin.ID)
	if err != nil {
		return
	}
	resp.Token = adminUserToken.Token
	return
}

func AdminLogout(ctx context.Context, req model.AdminLogoutReq) (resp model.AdminLogoutResp, err error) {
	err = handler.ClearUserToken(ctx, req.UserID)
	return
}

func AdminChangePassword(ctx context.Context, req model.AdminChangePasswordReq) (resp model.AdminChangePasswordResp, err error) {
	var (
		adminUserQ = sqlmodel.AdminUserColumns
		adminUser  sqlmodel.AdminUser
	)
	// 校验账户是否存在
	err = dao.FetchAdminUser(ctx, &adminUser, dao.And(adminUserQ.ID.Eq(req.UserID)))
	if err != nil {
		return
	}
	hashedPwd, err := bcrypt.GenerateFromPassword([]byte(req.NewPassword), bcrypt.DefaultCost)
	if err != nil {
		return
	}
	adminUser.Password = string(hashedPwd)
	_, _ = dao.UpdateAdminUser(ctx, &adminUser)
	return
}

func GetAdminInfo(ctx context.Context, req model.GetAdminInfoReq) (resp model.GetAdminInfoResp, err error) {
	var (
		userQ = sqlmodel.AdminUserColumns
		user  sqlmodel.AdminUser
	)
	err = dao.FetchAdminUser(ctx, &user, userQ.ID.Eq(req.UserID))
	if err != nil {
		return
	}
	resp.ID = int(user.ID)
	resp.Name = user.Username
	resp.Avatar = fmt.Sprintf("https://cravatar.cn/avatar/%s?d=monsterid", user.Username)
	resp.Roles = handler.GetPermissionList(ctx, req.UserID)
	return
}
