//generated by lazy
//author: seanlan

package service

import (
	"context"
	"token-payment/internal/model"
)

func GetApplicationList(ctx context.Context, req model.GetApplicationListReq) (resp model.GetApplicationListResp, err error) {
	return
}
