//generated by lazy
//author: seanlan

package service

import (
	"context"
	"gorm.io/gorm/clause"
	"token-payment/internal/dao"
	"token-payment/internal/dao/sqlmodel"
	"token-payment/internal/model"
)

func GetChainList(ctx context.Context, req model.GetChainListReq) (resp model.GetChainListResp, err error) {
	var (
		chainQ = sqlmodel.ChainColumns
		params = make([]clause.Expression, 0)
	)
	// 查询链列表
	resp.Total, err = dao.CountChain(ctx, dao.And(params...))
	err = dao.FetchAllChain(ctx, &resp.List, dao.And(params...), req.Page, req.Size, chainQ.ID.Desc())
	return
}

func EditChain(ctx context.Context, req model.EditChainReq) (resp model.EditChainResp, err error) {
	var (
		chain = sqlmodel.Chain{
			ID:          req.ID,
			ChainSymbol: req.ChainSymbol,
			Name:        req.Name,
			ChainID:     req.ChainID,
			Currency:    req.Currency,
			ChainType:   req.ChainType,
			Confirm:     req.Confirm,
			Gas:         req.Gas,
			GasPrice:    req.GasPrice,
			Concurrent:  req.Concurrent,
			Watch:       req.Watch,
		}
	)
	err = dao.SaveChain(ctx, &chain)
	return
}

func GetChainRPCList(ctx context.Context, req model.GetChainRPCListReq) (resp model.GetChainRPCListResp, err error) {
	var (
		rpcQ   = sqlmodel.ChainRPCColumns
		params = make([]clause.Expression, 0)
	)
	if req.ChainSymbol != "" {
		params = append(params, rpcQ.ChainSymbol.Eq(req.ChainSymbol))
	}
	// 查询链RPC列表
	resp.Total, err = dao.CountChainRPC(ctx, dao.And(params...))
	err = dao.FetchAllChainRPC(ctx, &resp.List, dao.And(params...), req.Page, req.Size, rpcQ.ID.Desc())
	return
}

func EditChainRPC(ctx context.Context, req model.EditChainRPCReq) (resp model.EditChainRPCResp, err error) {
	var (
		rpc = sqlmodel.ChainRPC{
			ID:          req.ID,
			ChainSymbol: req.ChainSymbol,
			RPCURL:      req.RPCUrl,
			Disable:     req.Disable,
		}
	)
	err = dao.SaveChainRPC(ctx, &rpc)
	return
}

func DeleteChainRPC(ctx context.Context, req model.DeleteChainRPCReq) (resp model.DeleteChainRPCResp, err error) {
	_, err = dao.DeleteChainRPC(ctx, sqlmodel.ChainRPCColumns.ID.Eq(req.ID))
	return
}

func GetTokenList(ctx context.Context, req model.GetTokenListReq) (resp model.GetTokenListResp, err error) {
	var (
		tokenQ = sqlmodel.ChainTokenColumns
		params = make([]clause.Expression, 0)
	)
	if req.ChainSymbol != "" {
		params = append(params, tokenQ.ChainSymbol.Eq(req.ChainSymbol))
	}
	// 查询链Token列表
	resp.Total, err = dao.CountChainToken(ctx, dao.And(params...))
	err = dao.FetchAllChainToken(ctx, &resp.List, dao.And(params...), req.Page, req.Size, tokenQ.ID.Desc())
	return
}

func EditToken(ctx context.Context, req model.EditTokenReq) (resp model.EditTokenResp, err error) {
	var (
		token = sqlmodel.ChainToken{
			ID:              req.ID,
			ChainSymbol:     req.ChainSymbol,
			ContractAddress: req.ContractAddress,
			Name:            req.Name,
			Symbol:          req.Symbol,
			Decimals:        req.Decimals,
			Threshold:       req.Threshold,
			GasFee:          req.GasFee,
			ArrangeSwitch:   req.ArrangeSwitch,
		}
	)
	err = dao.SaveChainToken(ctx, &token)
	return
}

func DeleteToken(ctx context.Context, req model.DeleteTokenReq) (resp model.DeleteTokenResp, err error) {
	_, err = dao.DeleteChainToken(ctx, sqlmodel.ChainTokenColumns.ID.Eq(req.ID))
	return
}
