//generated by lazy
//author: seanlan

package service

import (
	"context"
	"fmt"
	"token-payment/internal/constant"
	"token-payment/internal/dao"
	"token-payment/internal/dao/sqlmodel"
	"token-payment/internal/e"
	"token-payment/internal/handler"
	"token-payment/internal/model"
)

// GetAllGroup 获取所有角色分组
func GetAllGroup(ctx context.Context, req model.GetAllGroupReq) (resp model.GetAllGroupResp, err error) {
	var (
		groups []sqlmodel.AdminGroup
	)
	err = dao.FetchAllAdminGroup(ctx, &groups, nil, 0, 0)
	if err != nil {
		return
	}
	resp.List = make([]model.Group, 0)
	for _, group := range groups {
		var permissions []int
		dao.DB.Model(&sqlmodel.AdminGroupPermission{}).Where("group_id = ?", group.ID).Pluck("permission_id", &permissions)
		resp.List = append(resp.List, model.Group{
			ID:          int(group.ID),
			Name:        group.Name,
			Permissions: permissions,
		})
	}
	return
}

// AddGroup 添加角色分组
func AddGroup(ctx context.Context, req model.AddGroupReq) (resp model.AddGroupResp, err error) {
	var (
		group = sqlmodel.AdminGroup{
			Name: req.Name,
		}
		groupPermissions = make([]sqlmodel.AdminGroupPermission, 0)
	)
	_, err = dao.AddAdminGroup(ctx, &group)
	if err != nil {
		return
	}
	for _, permission := range req.Permissions {
		groupPermissions = append(groupPermissions, sqlmodel.AdminGroupPermission{
			GroupID:      int64(group.ID),
			PermissionID: int64(permission),
		})
	}
	_, err = dao.AddsAdminGroupPermission(ctx, &groupPermissions)
	if err != nil {
		return
	}
	// 添加用户日志
	handler.AddAdminLog(ctx, req.UserID,
		fmt.Sprintf("添加角色: [%d] %s", group.ID, group.Name),
		constant.AssetTypeGroup, int64(group.ID))
	return
}

// EditGroup 更新角色分组
func EditGroup(ctx context.Context, req model.EditGroupReq) (resp model.EditGroupResp, err error) {
	var (
		groupQ = sqlmodel.AdminGroupColumns
		gpQ    = sqlmodel.AdminGroupPermissionColumns
		group  sqlmodel.AdminGroup
	)
	err = dao.FetchAdminGroup(ctx, &group, groupQ.ID.Eq(req.GroupID))
	if err != nil {
		err = e.ErrorGroupIDNotExist
		return
	}
	group.Name = req.Name
	_, err = dao.UpdateAdminGroup(ctx, &group)
	if err != nil {
		return
	}
	// 删除原有权限
	_, _ = dao.DeleteAdminGroupPermission(ctx, gpQ.GroupID.Eq(req.GroupID))
	// 添加新权限
	if len(req.Permissions) > 0 {
		var groupPermissions = make([]sqlmodel.AdminGroupPermission, 0)
		for _, permission := range req.Permissions {
			groupPermissions = append(groupPermissions, sqlmodel.AdminGroupPermission{
				GroupID:      int64(group.ID),
				PermissionID: int64(permission),
			})
		}
		_, err = dao.AddsAdminGroupPermission(ctx, &groupPermissions)
		if err != nil {
			return
		}
	}
	// 添加用户日志
	handler.AddAdminLog(ctx, req.UserID,
		fmt.Sprintf("编辑角色: [%d] %s", group.ID, group.Name),
		constant.AssetTypeGroup, int64(group.ID))
	return
}
