//generated by lazy
//author: seanlan

package service

import (
	"context"
	"token-payment/internal/dao"
	"token-payment/internal/dao/sqlmodel"
	"token-payment/internal/model"
)

// GetAllPermission 获取所有权限
func GetAllPermission(ctx context.Context, req model.GetAllPermissionReq) (resp model.GetAllPermissionResp, err error) {
	var (
		permissions       []sqlmodel.AdminPermission
		permissionTypeMap = make(map[string]*model.PermissionType)
	)
	err = dao.FetchAllAdminPermission(ctx, &permissions, nil, 0, 0)
	if err != nil {
		return
	}
	for _, permission := range permissions {
		if _, ok := permissionTypeMap[permission.Type]; !ok {
			permissionTypeMap[permission.Type] = &model.PermissionType{
				Type:        permission.Type,
				Permissions: make([]sqlmodel.AdminPermission, 0),
			}
		}
		permissionType := permissionTypeMap[permission.Type]
		permissionType.Permissions = append(permissionType.Permissions, permission)
	}
	resp.List = make([]model.PermissionType, 0)
	for _, permissionType := range permissionTypeMap {
		resp.List = append(resp.List, *permissionType)
	}
	return
}
