//generated by lazy
//author: seanlan

package service

import (
	"context"
	"fmt"
	"golang.org/x/crypto/bcrypt"
	"gorm.io/gorm/clause"
	"time"
	"token-payment/internal/constant"
	"token-payment/internal/dao"
	"token-payment/internal/dao/sqlmodel"
	"token-payment/internal/e"
	"token-payment/internal/handler"
	"token-payment/internal/model"
)

// AddStaff 添加账户
func AddStaff(ctx context.Context, req model.AddStaffReq) (resp model.AddStaffResp, err error) {
	var (
		now   = time.Now()
		count int64
	)
	// 判断账户是否存在
	count, err = dao.CountAdminUser(ctx, sqlmodel.AdminUserColumns.Account.Eq(req.Account))
	if err != nil {
		return
	}
	if count > 0 {
		err = e.ErrorAccountExist
		return
	}
	hashedPwd, err := bcrypt.GenerateFromPassword([]byte(req.Password), bcrypt.DefaultCost)
	if err != nil {
		return
	}
	user := sqlmodel.AdminUser{
		Account:  req.Account,
		Password: string(hashedPwd),
		CreateAt: now.Unix(),
		Email:    req.Email,
		Phone:    req.Phone,
		Username: req.Username,
	}
	_, err = dao.AddAdminUser(ctx, &user)
	if err != nil {
		return
	}
	// 添加用户群组
	if req.Group > 0 {
		// 校验群组ID是否存在
		count, err = dao.CountAdminGroup(ctx, sqlmodel.AdminGroupColumns.ID.Eq(req.Group))
		if err != nil {
			return
		}
		if count == 0 {
			err = e.ErrorGroupIDNotExist
			return
		}
		var groupUserQ = sqlmodel.AdminGroupUserColumns
		_, err = dao.UpsertAdminGroupUser(ctx, &sqlmodel.AdminGroupUser{
			GroupID: req.Group,
			UserID:  user.ID,
		}, dao.M{
			groupUserQ.GroupID.FieldName: int32(req.Group),
		})
		if err != nil {
			return
		}
	}
	// 添加权限
	if len(req.Permissions) > 0 {
		// 校验群组ID是否存在
		count, err = dao.CountAdminPermission(ctx, sqlmodel.AdminPermissionColumns.ID.In(req.Permissions))
		if err != nil {
			return
		}
		if count != int64(len(req.Permissions)) {
			err = e.ErrorPermissionIDNotExist
			return
		}
		userPermissions := make([]sqlmodel.AdminUserPermission, 0)
		for _, permission := range req.Permissions {
			userPermissions = append(userPermissions, sqlmodel.AdminUserPermission{
				PermissionID: int64(permission),
				UserID:       int64(user.ID),
			})
		}
		_, err = dao.AddsAdminUserPermission(ctx, &userPermissions)
		if err != nil {
			return
		}
	}
	// 添加用户日志
	handler.AddAdminLog(ctx, req.UserID,
		fmt.Sprintf("添加账户: [%d] %s", user.ID, req.Account),
		constant.AssetTypeUser, int64(user.ID))
	return
}

// StaffList 获取员工列表
func StaffList(ctx context.Context, req model.StaffListReq) (resp model.StaffListResp, err error) {
	var (
		userQ    = sqlmodel.AdminUserColumns
		userList []sqlmodel.AdminUser
		params   = make([]clause.Expression, 0)
	)
	resp.Total, err = dao.CountAdminUser(ctx, dao.And(params...))
	if err != nil {
		return
	}
	err = dao.FetchAllAdminUser(ctx, &userList, dao.And(params...), req.Page, req.Size, userQ.ID.Desc())
	if err != nil {
		return
	}
	dao.DB.Model(&sqlmodel.AdminUser{}).Select(
		"`admin_user`.*, `admin_group`.`id` as `group_id`, `admin_group`.`name` as `group_name`",
	).Joins(
		"LEFT JOIN `admin_group_user` ON `admin_group_user`.`user_id` = `admin_user`.`id`",
	).Joins(
		"LEFT JOIN `admin_group` ON `admin_group_user`.`group_id` = `admin_group`.`id`",
	).Where(dao.And(params...)).Limit(req.Size).Offset((req.Page - 1) * req.Size).Find(&resp.List)
	return
}

// EditStaff 编辑账户
func EditStaff(ctx context.Context, req model.EditStaffReq) (resp model.EditStaffResp, err error) {
	var (
		adminUserQ = sqlmodel.AdminUserColumns
		adminUser  sqlmodel.AdminUser
		count      int64
	)
	// 校验账户是否存在
	err = dao.FetchAdminUser(ctx, &adminUser, dao.And(adminUserQ.ID.Eq(req.StaffID)))
	if err != nil {
		return
	}
	if adminUser.IsSuper == 1 {
		err = e.ErrorSuperUserNotEdit
		return
	}
	// 修改账户信息
	adminUser.Username = req.Username
	adminUser.Email = req.Email
	adminUser.Phone = req.Phone
	_, err = dao.UpdateAdminUser(ctx, &adminUser)
	if err != nil {
		return
	}
	// 修改账户群组
	var groupUserQ = sqlmodel.AdminGroupUserColumns
	if req.Group > 0 {
		// 校验群组ID是否存在
		count, err = dao.CountAdminGroup(ctx, sqlmodel.AdminGroupColumns.ID.Eq(req.Group))
		if err != nil {
			return
		}
		if count == 0 {
			err = e.ErrorGroupIDNotExist
			return
		}
		// 修改用户群组
		_, err = dao.UpsertAdminGroupUser(ctx,
			&sqlmodel.AdminGroupUser{
				GroupID: req.Group,
				UserID:  adminUser.ID,
			},
			dao.M{
				groupUserQ.GroupID.FieldName: int32(req.Group),
			})
	} else {
		// 删除账户群组
		_, err = dao.DeleteAdminGroupUser(ctx, dao.And(groupUserQ.UserID.Eq(req.StaffID)))
	}
	if err != nil {
		return
	}
	// 删除账户原有权限
	_, err = dao.DeleteAdminUserPermission(ctx, sqlmodel.AdminUserPermissionColumns.UserID.Eq(req.StaffID))
	// 添加权限
	if len(req.Permissions) > 0 {
		// 校验群组ID是否存在
		count, err = dao.CountAdminPermission(ctx, sqlmodel.AdminPermissionColumns.ID.In(req.Permissions))
		if err != nil {
			return
		}
		if count != int64(len(req.Permissions)) {
			err = e.ErrorPermissionIDNotExist
			return
		}
		userPermissions := make([]sqlmodel.AdminUserPermission, 0)
		for _, permission := range req.Permissions {
			userPermissions = append(userPermissions, sqlmodel.AdminUserPermission{
				PermissionID: int64(permission),
				UserID:       int64(adminUser.ID),
			})
		}
		_, err = dao.AddsAdminUserPermission(ctx, &userPermissions)
		if err != nil {
			return
		}
	}
	return
}

// StaffInfo 获取员工信息
func StaffInfo(ctx context.Context, req model.StaffInfoReq) (resp model.StaffInfoResp, err error) {
	var (
		adminUserQ = sqlmodel.AdminUserColumns
		adminUser  sqlmodel.AdminUser
	)
	// 校验账户是否存在
	err = dao.FetchAdminUser(ctx, &adminUser, dao.And(adminUserQ.ID.Eq(req.StaffID)))
	if err != nil {
		return
	}
	resp.Staff = model.StaffInfo{
		ID:       int64(adminUser.ID),
		Account:  adminUser.Account,
		Username: adminUser.Username,
		Phone:    adminUser.Phone,
		Email:    adminUser.Email,
		CreateAt: adminUser.CreateAt,
	}
	// 获取账户群组
	var (
		groupUserQ = sqlmodel.AdminGroupUserColumns
		groupUser  sqlmodel.AdminGroupUser
	)
	_ = dao.FetchAdminGroupUser(ctx, &groupUser, dao.And(groupUserQ.UserID.Eq(req.StaffID)))
	resp.Staff.Group = int(groupUser.GroupID)
	// 获取账户群组权限
	var (
		gpQ   = sqlmodel.AdminGroupPermissionColumns
		gpIDs []int
	)
	dao.DB.Model(&sqlmodel.AdminGroupPermission{}).Where(gpQ.GroupID.Eq(groupUser.GroupID)).Pluck(gpQ.PermissionID.FieldName, &gpIDs)
	resp.Staff.GroupPermissions = gpIDs
	// 获取账户权限
	var (
		upQ   = sqlmodel.AdminUserPermissionColumns
		upIDs []int
	)
	dao.DB.Model(&sqlmodel.AdminUserPermission{}).Where(upQ.UserID.Eq(req.StaffID)).Pluck(upQ.PermissionID.FieldName, &upIDs)
	resp.Staff.Permissions = upIDs
	return
}

// StaffRePassword 重置账户密码
func StaffRePassword(ctx context.Context, req model.StaffRePasswordReq) (resp model.StaffRePasswordResp, err error) {
	var (
		adminUserQ = sqlmodel.AdminUserColumns
		adminUser  sqlmodel.AdminUser
	)
	// 校验账户是否存在
	err = dao.FetchAdminUser(ctx, &adminUser, dao.And(adminUserQ.ID.Eq(req.StaffID)))
	if err != nil {
		return
	}
	if adminUser.IsSuper == 1 {
		err = e.ErrorSuperUserNotEdit
		return
	}
	hashedPwd, err := bcrypt.GenerateFromPassword([]byte(req.Password), bcrypt.DefaultCost)
	if err != nil {
		return
	}
	adminUser.Password = string(hashedPwd)
	_, _ = dao.UpdateAdminUser(ctx, &adminUser)
	_ = handler.UserLogout(ctx, int32(adminUser.ID))
	// 添加用户日志
	handler.AddAdminLog(ctx, req.UserID,
		fmt.Sprintf("重置密码: [%d] %s", adminUser.ID, adminUser.Account),
		constant.AssetTypeUser, int64(adminUser.ID))
	return
}

// StaffLogs 获取账户日志
func StaffLogs(ctx context.Context, req model.StaffLogsReq) (resp model.StaffLogsResp, err error) {
	var (
		logQ    = sqlmodel.AdminLogColumns
		logs    []sqlmodel.AdminLog
		userIDs []int64
		params  = make([]clause.Expression, 0)
	)
	if req.StaffID > 0 {
		params = append(params, logQ.UserID.Eq(req.StaffID))
	}
	if req.DateStart != "" {
		star, _ := time.ParseInLocation("2006-01-02", req.DateStart, time.Local)
		params = append(params, logQ.CreateAt.Gte(star.Unix()))
	}
	if req.DateEnd != "" {
		end, _ := time.ParseInLocation("2006-01-02", req.DateEnd, time.Local)
		params = append(params, logQ.CreateAt.Lte(end.Unix()+86400-1))
	}
	resp.Total, err = dao.CountAdminLog(ctx, dao.And(params...))
	if err != nil {
		return
	}
	resp.List = make([]model.StaffLogItem, 0)
	err = dao.FetchAllAdminLog(ctx, &logs, dao.And(params...), req.Page, req.Size, logQ.ID.Desc())
	if err != nil {
		return
	}
	if len(logs) == 0 {
		return
	}
	for _, log := range logs {
		userIDs = append(userIDs, log.UserID)
	}
	userMap := handler.GetUserMap(ctx, userIDs)
	for _, log := range logs {
		user := userMap[log.UserID]
		resp.List = append(resp.List, model.StaffLogItem{
			AdminLog: log,
			Staff:    user,
		})
	}
	return
}
