//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameAdminGroup = "admin_group"

var AdminGroupColumns = struct {
	ID   FieldBase
	Name FieldBase
}{
	ID:   FieldBase{"id", "id"},
	Name: FieldBase{"name", "name"},
}

type AdminGroup struct {
	ID   int32  `json:"id" gorm:"column:id;type:int;primaryKey;autoIncrement"` //
	Name string `json:"name" gorm:"column:name;type:varchar;not null"`         //组名
}

// TableName AdminGroup's table name
func (*AdminGroup) TableName() string {
	return TableNameAdminGroup
}
