//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameAdminUserMessage = "admin_user_message"

var AdminUserMessageColumns = struct {
	ID       FieldBase
	UserID   FieldBase
	Title    FieldBase
	Message  FieldBase
	Path     FieldBase
	IsRead   FieldBase
	CreateAt FieldBase
}{
	ID:       FieldBase{"`id`"},
	UserID:   FieldBase{"`user_id`"},
	Title:    FieldBase{"`title`"},
	Message:  FieldBase{"`message`"},
	Path:     FieldBase{"`path`"},
	IsRead:   FieldBase{"`is_read`"},
	CreateAt: FieldBase{"`create_at`"},
}

type AdminUserMessage struct {
	ID       int64  `json:"id" gorm:"column:id;type:bigint;primaryKey;autoIncrement"` //
	UserID   int64  `json:"user_id" gorm:"column:user_id;type:bigint;not null"`       //用户ID
	Title    string `json:"title" gorm:"column:title;type:varchar;not null"`          //标题
	Message  string `json:"message" gorm:"column:message;type:varchar;not null"`      //消息
	Path     string `json:"path" gorm:"column:path;type:varchar;not null"`            //资源路径
	IsRead   int32  `json:"is_read" gorm:"column:is_read;type:int;not null"`          //是否处理
	CreateAt int64  `json:"create_at" gorm:"column:create_at;type:bigint;not null"`   //消息时间
}

// TableName AdminUserMessage's table name
func (*AdminUserMessage) TableName() string {
	return TableNameAdminUserMessage
}
