//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameAdminUser = "admin_user"

var AdminUserColumns = struct {
	ID          FieldBase
	Account     FieldBase
	Password    FieldBase
	Username    FieldBase
	Phone       FieldBase
	Email       FieldBase
	IsSuper     FieldBase
	IsFrozen    FieldBase
	IsDelete    FieldBase
	HideArticle FieldBase
	CreateAt    FieldBase
}{
	ID:          FieldBase{"id", "id"},
	Account:     FieldBase{"account", "account"},
	Password:    FieldBase{"password", "password"},
	Username:    FieldBase{"username", "username"},
	Phone:       FieldBase{"phone", "phone"},
	Email:       FieldBase{"email", "email"},
	IsSuper:     FieldBase{"is_super", "is_super"},
	IsFrozen:    FieldBase{"is_frozen", "is_frozen"},
	IsDelete:    FieldBase{"is_delete", "is_delete"},
	HideArticle: FieldBase{"hide_article", "hide_article"},
	CreateAt:    FieldBase{"create_at", "create_at"},
}

type AdminUser struct {
	ID          int32  `json:"id" gorm:"column:id;type:int;primaryKey;autoIncrement"`     //
	Account     string `json:"account" gorm:"column:account;type:varchar;not null"`       //账号
	Password    string `json:"password" gorm:"column:password;type:varchar;not null"`     //密码
	Username    string `json:"username" gorm:"column:username;type:varchar;not null"`     //用户名
	Phone       string `json:"phone" gorm:"column:phone;type:varchar;not null"`           //手机号
	Email       string `json:"email" gorm:"column:email;type:varchar;not null"`           //电子邮箱
	IsSuper     int32  `json:"is_super" gorm:"column:is_super;type:int;not null"`         //是否超级用户
	IsFrozen    int32  `json:"is_frozen" gorm:"column:is_frozen;type:int;not null"`       //是否被封禁
	IsDelete    int32  `json:"is_delete" gorm:"column:is_delete;type:int;not null"`       //是否已删除
	HideArticle int32  `json:"hide_article" gorm:"column:hide_article;type:int;not null"` //是否隐藏稿件
	CreateAt    int64  `json:"create_at" gorm:"column:create_at;type:bigint;not null"`    //创建时间
}

// TableName AdminUser's table name
func (*AdminUser) TableName() string {
	return TableNameAdminUser
}
