//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameAdminGroupPermission = "admin_group_permission"

var AdminGroupPermissionColumns = struct {
	ID           FieldBase
	GroupID      FieldBase
	PermissionID FieldBase
}{
	ID:           FieldBase{"id", "id"},
	GroupID:      FieldBase{"group_id", "group_id"},
	PermissionID: FieldBase{"permission_id", "permission_id"},
}

type AdminGroupPermission struct {
	ID           int64 `json:"id" gorm:"column:id;type:bigint;primaryKey;autoIncrement"`       //
	GroupID      int64 `json:"group_id" gorm:"column:group_id;type:bigint;not null"`           //组ID
	PermissionID int64 `json:"permission_id" gorm:"column:permission_id;type:bigint;not null"` //权限ID
}

// TableName AdminGroupPermission's table name
func (*AdminGroupPermission) TableName() string {
	return TableNameAdminGroupPermission
}
