//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameAdminUser = "admin_user"

var AdminUserColumns = struct {
	ID       FieldBase
	Account  FieldBase
	Password FieldBase
	Username FieldBase
	Phone    FieldBase
	Email    FieldBase
	IsSuper  FieldBase
	CreateAt FieldBase
}{
	ID:       FieldBase{"id", "admin_user.id"},
	Account:  FieldBase{"account", "admin_user.account"},
	Password: FieldBase{"password", "admin_user.password"},
	Username: FieldBase{"username", "admin_user.username"},
	Phone:    FieldBase{"phone", "admin_user.phone"},
	Email:    FieldBase{"email", "admin_user.email"},
	IsSuper:  FieldBase{"is_super", "admin_user.is_super"},
	CreateAt: FieldBase{"create_at", "admin_user.create_at"},
}

type AdminUser struct {
	ID       int64  `json:"id" gorm:"column:id;type:bigint;primaryKey;autoIncrement"`   //
	Account  string `json:"account" gorm:"column:account;type:varchar(200);not null"`   //账号
	Password string `json:"password" gorm:"column:password;type:varchar(200);not null"` //密码
	Username string `json:"username" gorm:"column:username;type:varchar(200);not null"` //用户名
	Phone    string `json:"phone" gorm:"column:phone;type:varchar(200);not null"`       //手机号
	Email    string `json:"email" gorm:"column:email;type:varchar(200);not null"`       //电子邮箱
	IsSuper  int32  `json:"is_super" gorm:"column:is_super;type:int;not null"`          //是否超级用户
	CreateAt int64  `json:"create_at" gorm:"column:create_at;type:bigint;not null"`     //创建时间
}

// TableName AdminUser's table name
func (*AdminUser) TableName() string {
	return TableNameAdminUser
}
