//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameAdminGroupUser = "admin_group_user"

var AdminGroupUserColumns = struct {
	ID      FieldBase
	UserID  FieldBase
	GroupID FieldBase
}{
	ID:      FieldBase{"id", "id"},
	UserID:  FieldBase{"user_id", "user_id"},
	GroupID: FieldBase{"group_id", "group_id"},
}

type AdminGroupUser struct {
	ID      int32 `json:"id" gorm:"column:id;type:int;primaryKey;autoIncrement"` //
	UserID  int32 `json:"user_id" gorm:"column:user_id;type:int;not null"`       //用户ID
	GroupID int32 `json:"group_id" gorm:"column:group_id;type:int;not null"`     //组ID
}

// TableName AdminGroupUser's table name
func (*AdminGroupUser) TableName() string {
	return TableNameAdminGroupUser
}
