//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameAdminPermission = "admin_permission"

var AdminPermissionColumns = struct {
	ID   FieldBase
	Name FieldBase
	Code FieldBase
	Type FieldBase
}{
	ID:   FieldBase{"id", "admin_permission.id"},
	Name: FieldBase{"name", "admin_permission.name"},
	Code: FieldBase{"code", "admin_permission.code"},
	Type: FieldBase{"type", "admin_permission.type"},
}

type AdminPermission struct {
	ID   int64  `json:"id" gorm:"column:id;type:bigint;primaryKey;autoIncrement"` //
	Name string `json:"name" gorm:"column:name;type:varchar;not null"`            //权限名称
	Code string `json:"code" gorm:"column:code;type:varchar;not null"`            //权限代码
	Type string `json:"type" gorm:"column:type;type:varchar;not null"`            //权限类型
}

// TableName AdminPermission's table name
func (*AdminPermission) TableName() string {
	return TableNameAdminPermission
}
