//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameAppApplication = "app_application"

var AppApplicationColumns = struct {
	AppKey    FieldBase
	AppName   FieldBase
	AppSecret FieldBase
	CreateAt  FieldBase
	HookURL   FieldBase
	ID        FieldBase
}{
	AppKey:    FieldBase{"`app_key`"},
	AppName:   FieldBase{"`app_name`"},
	AppSecret: FieldBase{"`app_secret`"},
	CreateAt:  FieldBase{"`create_at`"},
	HookURL:   FieldBase{"`hook_url`"},
	ID:        FieldBase{"`id`"},
}

type AppApplication struct {
	AppKey    string `json:"app_key" gorm:"column:app_key;type:varchar(200);not null"`               //app key
	AppName   string `json:"app_name" gorm:"column:app_name;type:varchar(200);not null"`             //app name
	AppSecret string `json:"app_secret" gorm:"column:app_secret;type:varchar(200);not null"`         //app secret
	CreateAt  int64  `json:"create_at" gorm:"column:create_at;type:bigint;not null"`                 //创建时间
	HookURL   string `json:"hook_url" gorm:"column:hook_url;type:varchar(512);not null"`             //通知url
	ID        uint64 `json:"id" gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true"` //
}

// TableName AppApplication's table name
func (*AppApplication) TableName() string {
	return TableNameAppApplication
}
