//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameAppChainRechargeTx = "app_chain_recharge_tx"

var AppChainRechargeTxColumns = struct {
	ID              FieldBase
	AppKey          FieldBase
	ChainSymbol     FieldBase
	TokenSymbol     FieldBase
	BlockNumber     FieldBase
	BlockHash       FieldBase
	TxHash          FieldBase
	BlockTime       FieldBase
	From            FieldBase
	To              FieldBase
	ContractAddress FieldBase
	TokenID         FieldBase
	Value           FieldBase
	Index           FieldBase
	BatchIndex      FieldBase
	Confirmations   FieldBase
	Removed         FieldBase
}{
	ID:              FieldBase{"`id`"},
	AppKey:          FieldBase{"`app_key`"},
	ChainSymbol:     FieldBase{"`chain_symbol`"},
	TokenSymbol:     FieldBase{"`token_symbol`"},
	BlockNumber:     FieldBase{"`block_number`"},
	BlockHash:       FieldBase{"`block_hash`"},
	TxHash:          FieldBase{"`tx_hash`"},
	BlockTime:       FieldBase{"`block_time`"},
	From:            FieldBase{"`from`"},
	To:              FieldBase{"`to`"},
	ContractAddress: FieldBase{"`contract_address`"},
	TokenID:         FieldBase{"`token_id`"},
	Value:           FieldBase{"`value`"},
	Index:           FieldBase{"`index`"},
	BatchIndex:      FieldBase{"`batch_index`"},
	Confirmations:   FieldBase{"`confirmations`"},
	Removed:         FieldBase{"`removed`"},
}

type AppChainRechargeTx struct {
	ID              int64  `json:"id" gorm:"column:id;type:bigint;primaryKey;autoIncrement"`              //
	AppKey          string `json:"app_key" gorm:"column:app_key;type:varchar;not null"`                   //app key
	ChainSymbol     string `json:"chain_symbol" gorm:"column:chain_symbol;type:varchar;not null"`         //链的符号
	TokenSymbol     string `json:"token_symbol" gorm:"column:token_symbol;type:varchar;not null"`         //币种符号
	BlockNumber     int64  `json:"block_number" gorm:"column:block_number;type:bigint;not null"`          //区块高度
	BlockHash       string `json:"block_hash" gorm:"column:block_hash;type:varchar;not null"`             //区块hash
	TxHash          string `json:"tx_hash" gorm:"column:tx_hash;type:varchar;not null"`                   //交易hash
	BlockTime       int64  `json:"block_time" gorm:"column:block_time;type:bigint;not null"`              //区块时间
	From            string `json:"from" gorm:"column:from;type:varchar;not null"`                         //转出地址
	To              string `json:"to" gorm:"column:to;type:varchar;not null"`                             //转入地址
	ContractAddress string `json:"contract_address" gorm:"column:contract_address;type:varchar;not null"` //合约地址
	TokenID         string `json:"token_id" gorm:"column:token_id;type:varchar;not null"`                 //NFT的TokenID
	Value           string `json:"value" gorm:"column:value;type:varchar;not null"`                       //转账数量
	Index           int64  `json:"index" gorm:"column:index;type:bigint;not null"`                        //在交易中的序号
	BatchIndex      int64  `json:"batch_index" gorm:"column:batch_index;type:bigint;not null"`            //批量处理的交易序号
	Confirmations   int64  `json:"confirmations" gorm:"column:confirmations;type:bigint;not null"`        //当前确认数
	Removed         int32  `json:"removed" gorm:"column:removed;type:int;not null"`                       //交易是否被移除
}

// TableName AppChainRechargeTx's table name
func (*AppChainRechargeTx) TableName() string {
	return TableNameAppChainRechargeTx
}
