//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameAppApplication = "app_application"

var AppApplicationColumns = struct {
	ID        FieldBase
	AppKey    FieldBase
	AppSecret FieldBase
	AppName   FieldBase
	HookURL   FieldBase
	CreateAt  FieldBase
}{
	ID:        FieldBase{"`id`"},
	AppKey:    FieldBase{"`app_key`"},
	AppSecret: FieldBase{"`app_secret`"},
	AppName:   FieldBase{"`app_name`"},
	HookURL:   FieldBase{"`hook_url`"},
	CreateAt:  FieldBase{"`create_at`"},
}

type AppApplication struct {
	ID        int64  `json:"id" gorm:"column:id;type:bigint;primaryKey;autoIncrement"`  //
	AppKey    string `json:"app_key" gorm:"column:app_key;type:varchar;not null"`       //app key
	AppSecret string `json:"app_secret" gorm:"column:app_secret;type:varchar;not null"` //app secret
	AppName   string `json:"app_name" gorm:"column:app_name;type:varchar;not null"`     //app name
	HookURL   string `json:"hook_url" gorm:"column:hook_url;type:varchar;not null"`     //通知url
	CreateAt  int64  `json:"create_at" gorm:"column:create_at;type:bigint;not null"`    //创建时间
}

// TableName AppApplication's table name
func (*AppApplication) TableName() string {
	return TableNameAppApplication
}
