//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameApplicationChain = "application_chain"

var ApplicationChainColumns = struct {
	ID            FieldBase
	ApplicationID FieldBase
	ChainSymbol   FieldBase
	HotWallet     FieldBase
	ColdWallet    FieldBase
	FeeWallet     FieldBase
}{
	ID:            FieldBase{"id", "application_chain.id"},
	ApplicationID: FieldBase{"application_id", "application_chain.application_id"},
	ChainSymbol:   FieldBase{"chain_symbol", "application_chain.chain_symbol"},
	HotWallet:     FieldBase{"hot_wallet", "application_chain.hot_wallet"},
	ColdWallet:    FieldBase{"cold_wallet", "application_chain.cold_wallet"},
	FeeWallet:     FieldBase{"fee_wallet", "application_chain.fee_wallet"},
}

type ApplicationChain struct {
	ID            int64  `json:"id" gorm:"column:id;type:bigint;primaryKey;autoIncrement"`         //
	ApplicationID int64  `json:"application_id" gorm:"column:application_id;type:bigint;not null"` //应用id
	ChainSymbol   string `json:"chain_symbol" gorm:"column:chain_symbol;type:varchar;not null"`    //链的符号
	HotWallet     string `json:"hot_wallet" gorm:"column:hot_wallet;type:varchar;not null"`        //热钱包地址
	ColdWallet    string `json:"cold_wallet" gorm:"column:cold_wallet;type:varchar;not null"`      //冷钱包地址
	FeeWallet     string `json:"fee_wallet" gorm:"column:fee_wallet;type:varchar;not null"`        //零钱整理费用钱包
}

// TableName ApplicationChain's table name
func (*ApplicationChain) TableName() string {
	return TableNameApplicationChain
}
