//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameChainRPC = "chain_rpc"

var ChainRPCColumns = struct {
	ChainSymbol FieldBase
	Disable     FieldBase
	ID          FieldBase
	RPCURL      FieldBase
}{
	ChainSymbol: FieldBase{"`chain_symbol`"},
	Disable:     FieldBase{"`disable`"},
	ID:          FieldBase{"`id`"},
	RPCURL:      FieldBase{"`rpc_url`"},
}

type ChainRPC struct {
	ChainSymbol string `json:"chain_symbol" gorm:"column:chain_symbol;type:varchar(200);not null"`     //链的符号
	Disable     int32  `json:"disable" gorm:"column:disable;type:int;not null"`                        //是否可用
	ID          uint64 `json:"id" gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true"` //
	RPCURL      string `json:"rpc_url" gorm:"column:rpc_url;type:varchar(1024);not null"`              //rpc地址
}

// TableName ChainRPC's table name
func (*ChainRPC) TableName() string {
	return TableNameChainRPC
}
