//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameChainBlock = "chain_block"

var ChainBlockColumns = struct {
	BlockHash   FieldBase
	BlockNumber FieldBase
	ChainSymbol FieldBase
	Checked     FieldBase
	ID          FieldBase
	ParentHash  FieldBase
	Removed     FieldBase
}{
	BlockHash:   FieldBase{"`block_hash`"},
	BlockNumber: FieldBase{"`block_number`"},
	ChainSymbol: FieldBase{"`chain_symbol`"},
	Checked:     FieldBase{"`checked`"},
	ID:          FieldBase{"`id`"},
	ParentHash:  FieldBase{"`parent_hash`"},
	Removed:     FieldBase{"`removed`"},
}

type ChainBlock struct {
	BlockHash   string `json:"block_hash" gorm:"column:block_hash;type:varchar(100);not null"`         //区块hash值
	BlockNumber int64  `json:"block_number" gorm:"column:block_number;type:bigint;not null"`           //区块高度
	ChainSymbol string `json:"chain_symbol" gorm:"column:chain_symbol;type:varchar(200);not null"`     //链的符号
	Checked     int32  `json:"checked" gorm:"column:checked;type:int;not null"`                        //是否检测完成
	ID          uint64 `json:"id" gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true"` //
	ParentHash  string `json:"parent_hash" gorm:"column:parent_hash;type:varchar(100);not null"`       //上一个区块hash值
	Removed     int32  `json:"removed" gorm:"column:removed;type:int;not null"`                        //是否已移除
}

// TableName ChainBlock's table name
func (*ChainBlock) TableName() string {
	return TableNameChainBlock
}
