//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameChainWithdrawOrder = "chain_withdraw_order"

var ChainWithdrawOrderColumns = struct {
	ID                  FieldBase
	ApplicationID       FieldBase
	SerialNo            FieldBase
	ChainSymbol         FieldBase
	ContractAddress     FieldBase
	Symbol              FieldBase
	Value               FieldBase
	TokenID             FieldBase
	TxHash              FieldBase
	Nonce               FieldBase
	CreateAt            FieldBase
	Generated           FieldBase
	TransferSuccess     FieldBase
	TransferFailedTimes FieldBase
}{
	ID:                  FieldBase{"id", "id"},
	ApplicationID:       FieldBase{"application_id", "application_id"},
	SerialNo:            FieldBase{"serial_no", "serial_no"},
	ChainSymbol:         FieldBase{"chain_symbol", "chain_symbol"},
	ContractAddress:     FieldBase{"contract_address", "contract_address"},
	Symbol:              FieldBase{"symbol", "symbol"},
	Value:               FieldBase{"value", "value"},
	TokenID:             FieldBase{"token_id", "token_id"},
	TxHash:              FieldBase{"tx_hash", "tx_hash"},
	Nonce:               FieldBase{"nonce", "nonce"},
	CreateAt:            FieldBase{"create_at", "create_at"},
	Generated:           FieldBase{"generated", "generated"},
	TransferSuccess:     FieldBase{"transfer_success", "transfer_success"},
	TransferFailedTimes: FieldBase{"transfer_failed_times", "transfer_failed_times"},
}

type ChainWithdrawOrder struct {
	ID                  int64   `json:"id" gorm:"column:id;type:bigint;primaryKey;autoIncrement"`                    //
	ApplicationID       int64   `json:"application_id" gorm:"column:application_id;type:bigint;not null"`            //应用ID
	SerialNo            string  `json:"serial_no" gorm:"column:serial_no;type:varchar;not null"`                     //订单序列号
	ChainSymbol         string  `json:"chain_symbol" gorm:"column:chain_symbol;type:varchar;not null"`               //链的符号
	ContractAddress     string  `json:"contract_address" gorm:"column:contract_address;type:varchar;not null"`       //代币合约地址，如果是空表示是主币
	Symbol              string  `json:"symbol" gorm:"column:symbol;type:varchar;not null"`                           //代币符号
	Value               float64 `json:"value" gorm:"column:value;type:decimal;not null"`                             //数量
	TokenID             int64   `json:"token_id" gorm:"column:token_id;type:bigint;not null"`                        //tokenid （NFT）
	TxHash              string  `json:"tx_hash" gorm:"column:tx_hash;type:varchar;not null"`                         //交易hash值
	Nonce               int64   `json:"nonce" gorm:"column:nonce;type:bigint;not null"`                              //交易nonce
	CreateAt            int64   `json:"create_at" gorm:"column:create_at;type:bigint;not null"`                      //申请时间
	Generated           int32   `json:"generated" gorm:"column:generated;type:int;not null"`                         //是否生成
	TransferSuccess     int32   `json:"transfer_success" gorm:"column:transfer_success;type:tinyint;not null"`       //是否转账成功
	TransferFailedTimes int32   `json:"transfer_failed_times" gorm:"column:transfer_failed_times;type:int;not null"` //转账失败次数
}

// TableName ChainWithdrawOrder's table name
func (*ChainWithdrawOrder) TableName() string {
	return TableNameChainWithdrawOrder
}
