//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameChainRPC = "chain_rpc"

var ChainRPCColumns = struct {
	ID          FieldBase
	ChainSymbol FieldBase
	RPCURL      FieldBase
	Disable     FieldBase
}{
	ID:          FieldBase{"id", "id"},
	ChainSymbol: FieldBase{"chain_symbol", "chain_symbol"},
	RPCURL:      FieldBase{"rpc_url", "rpc_url"},
	Disable:     FieldBase{"disable", "disable"},
}

type ChainRPC struct {
	ID          int64  `json:"id" gorm:"column:id;type:bigint;primaryKey;autoIncrement"`      //
	ChainSymbol string `json:"chain_symbol" gorm:"column:chain_symbol;type:varchar;not null"` //链的符号
	RPCURL      string `json:"rpc_url" gorm:"column:rpc_url;type:varchar;not null"`           //rpc地址
	Disable     int32  `json:"disable" gorm:"column:disable;type:int;not null"`               //是否可用
}

// TableName ChainRPC's table name
func (*ChainRPC) TableName() string {
	return TableNameChainRPC
}
