//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameChainAddress = "chain_address"

var ChainAddressColumns = struct {
	ID            FieldBase
	ApplicationID FieldBase
	ChainSymbol   FieldBase
	Address       FieldBase
	EncKey        FieldBase
	Hook          FieldBase
	Watch         FieldBase
	CreateAt      FieldBase
	Used          FieldBase
}{
	ID:            FieldBase{"id", "chain_address.id"},
	ApplicationID: FieldBase{"application_id", "chain_address.application_id"},
	ChainSymbol:   FieldBase{"chain_symbol", "chain_address.chain_symbol"},
	Address:       FieldBase{"address", "chain_address.address"},
	EncKey:        FieldBase{"enc_key", "chain_address.enc_key"},
	Hook:          FieldBase{"hook", "chain_address.hook"},
	Watch:         FieldBase{"watch", "chain_address.watch"},
	CreateAt:      FieldBase{"create_at", "chain_address.create_at"},
	Used:          FieldBase{"used", "chain_address.used"},
}

type ChainAddress struct {
	ID            int64  `json:"id" gorm:"column:id;type:bigint;primaryKey;autoIncrement"`         //
	ApplicationID int64  `json:"application_id" gorm:"column:application_id;type:bigint;not null"` //应用ID
	ChainSymbol   string `json:"chain_symbol" gorm:"column:chain_symbol;type:varchar;not null"`    //链的符号
	Address       string `json:"address" gorm:"column:address;type:varchar;not null"`              //地址
	EncKey        string `json:"enc_key" gorm:"column:enc_key;type:varchar;not null"`              //加密后的私钥
	Hook          string `json:"hook" gorm:"column:hook;type:varchar;not null"`                    //到账变动通知url
	Watch         int32  `json:"watch" gorm:"column:watch;type:int;not null"`                      //是否监听
	CreateAt      int64  `json:"create_at" gorm:"column:create_at;type:bigint;not null"`           //创建时间
	Used          int32  `json:"used" gorm:"column:used;type:int;not null"`                        //是否已使用
}

// TableName ChainAddress's table name
func (*ChainAddress) TableName() string {
	return TableNameChainAddress
}
