//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameConfigChainRPC = "config_chain_rpc"

var ConfigChainRPCColumns = struct {
	ChainSymbol FieldBase
	ID          FieldBase
}{
	ChainSymbol: FieldBase{"`chain_symbol`"},
	ID:          FieldBase{"`id`"},
}

type ConfigChainRPC struct {
	ChainSymbol string `json:"chain_symbol" gorm:"column:chain_symbol;type:varchar(200);not null"`     //链的符号
	ID          uint64 `json:"id" gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true"` //
}

// TableName ConfigChainRPC's table name
func (*ConfigChainRPC) TableName() string {
	return TableNameConfigChainRPC
}
